name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: test/go.mod
          cache-dependency-path: test/go.sum

      - name: Install Carvel Tools
        run: |
          curl -L https://carvel.dev/install.sh | sudo bash
          ytt version

      - name: Render config
        run: make render

      - name: Template tests
        run: make test
